server:
  port: 9101
  servlet:
    context-path: /naicha-admin-api

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
  type-aliases-package: com.yu.**.entity.** # *Mapper.xml里resultType的类型别名
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto # id生成策略

spring:
  profiles:
    active: dev   # dev:开发环境 prod:生产环境
  jackson:
    time-zone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss # date format

  redis:
    database: 0 # 数据库索引
    host: redis.xxl.today
    port: 6379
    password: xxl123-+
    timeout: 1000

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/naicha?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root